# Generated by Django 5.2.17 on 2026-08-23 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_product_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('PRODUCT_DEACTIVATED', 'Product Deactivated'), ('STOCK_RECEIVED', 'Stock Received'), ('STOCK_ADDED', 'Stock Added'), ('STOCK_DEDUCTED', 'Stock Deducted'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('SHIPMENT_CREATED', 'Shipment Created'), ('SHIPMENT_RECEIVED', 'Shipment Received'), ('BATCH_CREATED', 'Batch Created'), ('STOCK_RETURNED', 'Stock Returned'), ('STOCK_DAMAGED', 'Stock Damaged'), ('STOCK_EXPIRED', 'Stock Expired'), ('BARCODE_GENERATED', 'Barcode Generated'), ('BARCODE_PRINTED', 'Barcode Printed')], max_length=30)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('sku_snapshot', models.CharField(blank=True, max_length=64)),
                ('barcode_snapshot', models.CharField(blank=True, max_length=64)),
                ('quantity_before', models.IntegerField(blank=True, null=True)),
                ('quantity_changed', models.IntegerField(blank=True, null=True)),
                ('quantity_after', models.IntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=30)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=50)),
                ('previous_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='inventory.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='inventory_i_action_5ef034_idx'), models.Index(fields=['user'], name='inventory_i_user_id_7f1b29_idx'), models.Index(fields=['product'], name='inventory_i_product_00d797_idx'), models.Index(fields=['created_at'], name='inventory_i_created_f38e2a_idx')],
            },
        ),
    ]
