# Generated by Django 5.2.17 on 2026-09-02 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryactivitylog',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_on_hand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='inventoryactivitylog',
            index=models.Index(fields=['activity_date'], name='inventory_i_activit_233dc7_idx'),
        ),
    ]
